### ISSUE TITLE
Router doesn't seem to sent an x-forwarded-for

### ISSUE THREAD

**Issue by reality** [Irrelon/node-irrelon-router#3]
This seems to cause issues with software such as Kiwiirc. Would try to patch this myself but I'm not sure how!

**Comment by Akxe** [comment]
Shouldn't this be closed now? As the new does send it if I recall correctly. And also that the issue is not meant to the last version.

**Comment by Irrelon** [comment]
I think that is correct. Closing now, can be reopened if it is in error.
