### ISSUE TITLE
When server is not avaible server crashe

### ISSUE THREAD

**Issue by Akxe** [Irrelon/node-irrelon-router#6]
When I demand server from routerTable, that is not avaible (not running for ex.), then the app crashe

    C:\Nodejs\Router\node_modules\http-proxy\lib\http-proxy\index.js:119
        throw err;
              ^
    Error: connect ECONNREFUSED
        at errnoException (net.js:904:11)
        at Object.afterConnect [as oncomplete] (net.js:895:19)
    13 Sep 22:44:35 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by Irrelon** [comment]
Is there any chance you'd be able to put together a fix for this and do a pull request? You are welcome to contribute if you have some time :)

**Comment by Akxe** [comment]
Well I was trying, but haven't succeeded.

**Comment by Akxe** [comment]
`proxy.web(req, res, { target: 'http://mytarget.com:8080' }, function(e) { ... });` You have to add error function to proxy.web and call 403 within... I would do it, but my server got just wiped :/

**Comment by Akxe** [comment]
Pull request made
